name: movie_app
description: A new Flutter project.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  # State Management
  flutter_bloc: ^8.1.3
  # Network
  dio: ^5.4.0
  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  # Utils
  logger: ^2.0.2+1
  equatable: ^2.0.5
  # Navigation
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flutter_flavorizr: ^2.2.3
  easy_localization: ^3.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/config/
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Movie App Dev"
      android:
        applicationId: "com.example.movie_app.dev"
      ios:
        bundleId: "com.example.movie_app.dev"

    qa:
      app:
        name: "Movie App QA"
      android:
        applicationId: "com.example.movie_app.qa"
      ios:
        bundleId: "com.example.movie_app.qa"

    prod:
      app:
        name: "Movie App"
      android:
        applicationId: "com.example.movie_app"
      ios:
        bundleId: "com.example.movie_app"
